### ISSUE TITLE
vim-taskwarrior truncates report on empty lines

### ISSUE THREAD

**Issue by tbabej** [farseer90718/vim-taskwarrior#103]
The default "task list" report displays empty lines between different projects (this easily configurable for any attribute in any report).

This behaviour breaks vim-taskwarrior, which displays only the tasks from the first displayed project, ignoring the rest of the report.

For reproducing, try with TW 2.4.0:

    $ task add pro:P1 taskP1
    $ task add pro:P2 taskP2

And in the vim-taskwarrior:

    :TW list

You should only see the ```taskP1``` in the report.

**Comment by farseer90718** [comment]
Please pull and retry.

**Comment by tbabej** [comment]
Yes, this fixes the issue. Thanks!
