### ISSUE TITLE
:TWContext

### ISSUE THREAD

**Issue by linuxcaffe** [farseer90718/vim-taskwarrior#111]
In v2.4.2, taskwarrior introduced an important new feature: context support. 
The idea is to limit task output with a set of filters (a "context") and those filters will persist until the context is cleared or changed.

The context command has a few subcommands: define, show, list, delete. In order to set a command, use "task context define \<name\> definition":
<pre>
task context define home +home -work
</pre>
after confirmation dialogs, that definition will be saved to taskrc as "context.home=+home -work"
To use this context, invoke it by name:
<pre>
task context home
</pre>
and taskrc setting "context:home" will be set, and subsequent lists will include "+home -work" filter.
This function is fully documented in man task.

vim-taskwarrior already "supports" task context, in that vim-tw reports will be filtered while context is set, but as of yet, vim-tw has no related commands.

This RFE is to request full context support with
:TWContext command, invoking a "Context: " prompt, showing current context (if any) and allowing the user to set (or unset) a context. Context subcommands (define, list, show, delete) should also be usable from this prompt. 
"@" should also be mapped, to invoke the :TWContext command, and the current context could be displayed in the status-bar/ airline.

**Comment by farseer90718** [comment]
Please try `TW context` with fixed completion

**Comment by linuxcaffe** [comment]
Works! 
Interestingly, the completion seems to have a herd time completing "context", also offering up "_context", 
but "TW context" a reasonable way to switch contexts with vim-tw, thanks Zc! 
(is there a chance of mapping ":TW context " to "@"?)

**Comment by farseer90718** [comment]
`map @ :TW context` will work, but I don't think it should be a default mapping.

**Comment by linuxcaffe** [comment]
OK! thanks Zc!
(maybe I'll update some docs, when I'm in the right context)
