### ISSUE TITLE
statusbar errors

### ISSUE THREAD

**Issue by linuxcaffe** [farseer90718/vim-taskwarrior#113]
I'm not sure where this is coming from, but I'm seeing some messed up status bar. It's been like this (for me) for a few weeks.

![vim-tw_status-bar-errors_screenshot](https://cloud.githubusercontent.com/assets/2353531/7297984/95389d84-e99a-11e4-8525-2f262099c04c.png)

I'm using an up-to-date vim-taskwarrior and vim-airline, I'm seeing the error with and without taskwiki active.

**Comment by farseer90718** [comment]
What's the value of b:context? And the output of "task context show" in shell？

**Comment by linuxcaffe** [comment]
The output of 'task context show' is "No context is currently applied." but the statusbar weirdness persists with or without a context setting. 

and I'm not sure how to issue the command 'b:context'

**Comment by farseer90718** [comment]
`:echo b:context`. Will you please try to figure out which line in `autoload/airline/extensions/taskwarrior.vim` caused this ? (probably between line 4-8). You may try to comment out part of those lines to see what happens.

**Comment by linuxcaffe** [comment]
So sorry, there doesn't seem to be a taskwarrior.vim in the airline extensions, either locally, or in the repo;
https://github.com/bling/vim-airline/tree/master/autoload/airline/extensions . otherwise, I would happily poke at it.

**Comment by farseer90718** [comment]
That file exists in this repo. Not in vim-airline

**Comment by linuxcaffe** [comment]
ohh. sorry for being such a dunce Zc, I'll test with the vim-tw file.

**Comment by farseer90718** [comment]
My bad, I should provide more details. Do feel sorry.

**Comment by linuxcaffe** [comment]
Commenting out lines in taskwarrior.vim seemed to have no effect. I'm stumped! :)

**Comment by farseer90718** [comment]
The output of `echo airline#statusline(1)`?

**Comment by linuxcaffe** [comment]
%{airline#check_mode(1)}%#airline_a#%( %#airline_a_bold#%{airline#util#wrap(airline#parts#mode(),0)}%#airline_a#%{airline#util#append(airline#pa
rts#paste(),0)}%{airline#util#append("",0)}%{airline#util#append(airline#parts#iminsert(),0)} %)%#airline_a_to_airline_b#▶%#airline_b#%( %{airli
ne#util#wrap(airline#extensions#branch#get_head(),0)} %)%#airline_b_to_airline_c#▶%#airline_c#%( %<%f%m %#airline_c_red#%{airline#util#wrap(airl
ine#parts#readonly(),0)}%#airline_c# %)%=%#airline_c_to_airline_x#◀%#airline_x#%( %{airline#util#prepend(airline#extensions#tagbar#currenttag(),
0)}%{airline#util#wrap(airline#parts#filetype(),0)} %)%#airline_x_to_airline_y#◀%#airline_y#%( %{airline#util#wrap(airline#parts#ffenc(),0)} %)%
#airline_y_to_airline_z#◀%#airline_z#%( %3p%% %{g:airline_symbols.linenr}%#airline_z_bold#%4l%#airline_z#:%3v  %)%(%#airline_z_to_airline_warnin
g#◀%#airline_warning#%( %{airline#util#wrap(airline#extensions#whitespace#check(),0)} %)%)

**Comment by farseer90718** [comment]
In a tw buffer?

**Comment by linuxcaffe** [comment]
.. uhh..no :) this was:
%{airline#check_mode(1)}%#airline_a# Taskwarrior %=%#airline_a_to_airline_x#◀%#airline_x# %{b:now} < %{b:task_report_columns[taskwarrior#data#cu
rrent_index()]} %#airline_x_to_airline_y#◀%#airline_y# %{b:sort} %#airline_y_to_airline_z#◀%#airline_z#%#airline_z_orange#%{airline#util#wrap("
2 ",0)}%#airline_z#< %{b:summary[0]} <%#airline_z_green#%{airline#util#wrap(" 105 ",0)}%#airline_z#< %{b:summary[2]}

**Comment by farseer90718** [comment]
OK, I think b:now caused this, execute this command `task active limit:1 rc.verbose:nothing rc.report.active.sort=start- rc.report.active.columns=start.active,start.age,id,description.desc rc.report.active.labels=A,Age,ID,Description` in shell should get 1-line output since verbose:nothing.

**Comment by linuxcaffe** [comment]
It does indeed produce a single line of output.. "b:now caused this"?

**Comment by farseer90718** [comment]
Should be no line of labels.
Pull and see whether 63c2ea3585905d6e5c37b553d8afbef39a061fb5 can fix your problem.

**Comment by linuxcaffe** [comment]
Sure does Zc! 
Thanks again, working perfectly now!
