### ISSUE TITLE
colortheme syntax questions

### ISSUE THREAD

**Issue by linuxcaffe** [farseer90718/vim-taskwarrior#115]
I had my first go at creating a colortheme to use specifically with vim-tw. I duplicated my favorite colortheme file, and made a few changes to ../syntax/taskreport.vim, changing some assignments like;
<pre>
highlight default link taskwarrior_tablehead   Search
highlight default link taskwarrior_field       Search
highlight default link taskwarrior_selected    LineNr
highlight default link taskwarrior_id          Operator
highlight default link taskwarrior_project     String
highlight default link taskwarrior_Status      Function
highlight default link taskwarrior_priority    Operator
highlight default link taskwarrior_due         SpecialKey
highlight default link taskwarrior_end         Keyword
highlight default link taskwarrior_description Normal
highlight default link taskwarrior_entry       SpecialKey
highlight default link taskwarrior_depends     Number
highlight default link taskwarrior_tags        Tag
highlight default link taskwarrior_uuid        Operator
highlight default link taskwarrior_urgency     Float
</pre>
but I realize this will be hard(er) to maintain, as vim-tw is updated. 
Is this a feasible approach? Can I "simply" override these in my .vimrc?

**Comment by farseer90718** [comment]
You can override those in .vimrc.

**Comment by linuxcaffe** [comment]
thanks!
