### ISSUE TITLE
Error on custom report

### ISSUE THREAD

**Issue by ravl1084** [farseer90718/vim-taskwarrior#116]
I'm using taskwarrior 2.2.0 and I have a custom report called `actions` that produces this output

    ID Project      Pri Description
    77 home         L   Make CD Rack

When I open vim and then do `:TW` I get this error:

    Error detected while processing function taskwarrior#log#history..taskwarrior#list:
    Line 52:
    E684: list index out of range: 0
    E116: Invalid arguments for function index(split(getline(1), ' '), b:task_report_labels[v:key]) != -1

After hitting enter to dismiss this message, my custom report appears, but if I move the cursor left and right, it moves based on the position of the columns on the previous view instead of the current one. Also, the per-column highlighting is showing per the previous view (i.e. a part of the Description column is highlighted where the due date of the previous view was)

**Comment by farseer90718** [comment]
Would you please provide the `actions` part of your taskrc?

**Comment by ravl1084** [comment]
Here it is:
    report.actions.description=Actionable items
    report.actions.columns=id,project,due,priority,description
    report.actions.sort=due+,priority-,depends+,project+
    report.actions.filter=+actions and status:pending and -BLOCKED

**Comment by farseer90718** [comment]
Well, you have to add `report.actions.labels=xx,xx,xx,xx,xx` to your taskrc, and `let g:task_report_command = ['actions']` to your vimrc.

**Comment by farseer90718** [comment]
Well, you have to add `report.actions.labels=xx,xx,xx,xx,xx` to your taskrc, and `let g:task_report_command = ['actions']` to your vimrc.

**Comment by ravl1084** [comment]
Thank you! The labels did it.
