### ISSUE TITLE
Airline statusline funcref already added

### ISSUE THREAD

**Issue by durox** [farseer90718/vim-taskwarrior#118]
I just tried using vim-taskwarrior together with airline but everytime I open vim there comes the following error message: "The airline statusline funcref function('airline#extensions#taskwarrior#apply') 
has already been added."
Everything seems to work, but the error message is pretty annoying. I tried commenting out Line 40 in vim-taskwarrior/autoload/airline/extensions/taskwarrior.vim. The error message dissappears but there is no longer a customized airline. So not really ideal. Otherwise I don't know what to make out of the error message itself.

**Comment by farseer90718** [comment]
Would you please provide a minimal vimrc that will reproduce that problem?

**Comment by durox** [comment]
Thanks for your reply. I double-checked my installation and noticed that I made some errors when I transitioned from pathogen to Vundle. So after a clean Vundle setup the error doesnt occur anymore. Maybe pathogen and Vundle tried both to register the function and that caused the error. Totally my fault.
