### ISSUE TITLE
active row/ field/ cursor highlighting

### ISSUE THREAD

**Issue by linuxcaffe** [farseer90718/vim-taskwarrior#14]
<ignore>
Although vim-taskwarrior can determine the "selected" field by cursor position, it would be better if the cursor were one field wide, not one character wide, and using the arrow key, going right, right, right, should move the cursor field, field, field, not character, character, character. 
</ignore>

UPDATE: this request now for highlighting only, no change to cursor movement

**Comment by tecfu** [comment]
This was a great improvement and I definitely prefer:

```
let g:task_highlight_field = 1
``
