### ISSUE TITLE
Adding annotations with single ' in it, leads to error message.

### ISSUE THREAD

**Issue by jerri** [farseer90718/vim-taskwarrior#146]
Using a ' in the annotation text like e.g. `This doesn't work.`, I get an error message: 

```
Error detected while processing function taskwarrior#action#annotate[13]..taskwarrior#system_call:
line    2:
E484: Can't open file /tmp/vYGmlpb/35
```

**Comment by xarthurx** [comment]
This is not the issue of `vim-taskwarrior` but the command line call `task xx annotate <your anno>`.
`vim-taskwarrior` just simply call that shell command for adding annotations.

Using `\'` should work in this case.
