### ISSUE TITLE
Cant use Keys

### ISSUE THREAD

**Issue by pinpox** [farseer90718/vim-taskwarrior#95]
Hello,

I installled the plugin and it starts fine and shows the task when I tyoe :TW but I cant use any keys.
UP/DOWN works but I any other keybinding like "d" for marking as done doesn't do anything.

Here is my vimrc

http://pastie.org/9796866#10
Is this a Bug or do I have to change anything?

**Comment by binaryplease** [comment]
Perfect, thanks!
