### ISSUE TITLE
make TWReportInfo [id|uuid] available as a global vim command

### ISSUE THREAD

**Issue by linuxcaffe** [farseer90718/vim-taskwarrior#99]
In working with a new vimwiki-tasks implementation (https://github.com/tbabej/vimwiki-pytasks) I'd like the ability to open an info-window split, just like the vim-taskwarrior info command. If vim-tw offered the TaskInfo [id|uuid] command globally, we could just use that!

**Comment by farseer90718** [comment]
Actually you could use `TW [id|uuid] information`.

**Comment by linuxcaffe** [comment]
Of course! I forgot about the awsome flexibility of the raw ":TW" command!

Just playing with it in a wiki context, thinking about it globally, wondering how one could;

a) have the result of the ":TW foo" command, open in a splitted window, like the TWReportInfo

b) have the result of the ":TW foo" command, inserted as text at the cursor position

**Comment by farseer90718** [comment]
a) `:belowright split | TW foo`
b) `:read! task foo`

**Comment by linuxcaffe** [comment]
DAMN! THAT was easy!!! Thanks!

**Comment by linuxcaffe** [comment]
After experimenting with the suggestions above, I can see how those could be very useful, with some refinement. I still think that (again, in the vimwiki context) :TWReportInfo < ID > would be "just the ticket", so I'm re-opening this issue.

**Comment by linuxcaffe** [comment]
Yay! Perfect! Thanks!

**Comment by linuxcaffe** [comment]
I hate to do it, it seems like a small thing, but

If the bottom info split is the active window, has the cursor in it, then it would be much easier to close again, with CR or q, without having to change window first, for a better info-pop-up experience :-) thanks!
